version: '3.3'
services:
  client:
    hostname: client
    image: osm2pgsqlauto:client
    build:
      context: ./client
      dockerfile: client.Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 5049:4000
  pgadmin:
    build:
      context: .
      dockerfile: pgadmin.Dockerfile
    image: osm2pgsqlauto:pgadmin
    env_file: .env.pgadmin
    ports:
      -  5050:80
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
  qtorrent:
    hostname: qtorrent
    image: osm2pgsqlauto:qtorrent
    build:
      context: .
      dockerfile: qtorrent.Dockerfile
    env_file: .env.qtorrent
    volumes:
      - ./.qtorrent/config:/config
      - ./imports:/imports
    ports:
      - 6881:6881
      - 6969
      - 5051:8080
  graphql:
    hostname: graphql
    image: osm2pgsqlauto:graphql
    build:
      context: .
      dockerfile: postgraphql.Dockerfile
    env_file: .env.graphql
    ports:
      - 5052:5000
    volumes:
      - ./.graphql/entrypoint:/app/entrypoint
    restart: always
  postgres:
    hostname: postgres
    image: osm2pgsqlauto:postgres
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    env_file:
      - .env.postgres

    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
      - ./config:/docker-entrypoint-initdb.d
  imposm:
    hostname: imposm
    image: osm2pgsqlauto:imposm
    build:
      context: .
      dockerfile: imposm.Dockerfile
    env_file:
      - .env.postgres
      - .env.imposm
    ports:
      - 5433
    volumes:
      - ./imports:/imports
volumes:
  pgadmin: null
  client_modules: null